/**
 * @module nexus-cx/classifier/taxonomy
 * @description Static intent taxonomy for the deterministic classifier. Contains 19 domains,
 * 82 intents, and 629 exemplar phrases derived from historical CX interaction mining.
 *
 * This is the "frozen taxonomy" that the classifier runs against. In production, this
 * would be generated by an LLM-driven taxonomy discovery pipeline and versioned in a
 * configuration store. Locally, it serves as the ground truth for both TF-IDF and
 * embedding-based classification.
 *
 * Domain groups:
 *   - **Commercial CX** (5 domains, 20 intents): billing, technical_support, account, sales, general
 *   - **Treasury Core** (5 domains, 20 intents): tax_payments, savings_bonds, treasury_payments,
 *     debt_collection, currency_compliance
 *   - **Treasury Expanded** (9 domains, 42 intents): tax_filing, tax_identity, tax_compliance,
 *     treasury_accounts, foreign_tax, financial_crimes, government_payments, estate_gift_tax, business_tax
 *
 * Each intent entry contains:
 *   - `intent` {string} — unique intent identifier (e.g., 'billing_dispute')
 *   - `exemplars` {string[]} — training phrases for TF-IDF and embedding index
 *
 * @see {@link module:nexus-cx/classifier/classifier} Classifier (consumer)
 * @see {@link module:nexus-cx/classifier/reranker} Reranker (consumer)
 */

const TAXONOMY = {
  billing: {
    label: 'Billing',
    intents: {
      payment_issue: {
        label: 'Payment Issue',
        exemplars: [
          'my payment was declined',
          'cannot make a payment',
          'payment failed on my account',
          'credit card not working for payment',
          'autopay did not go through',
          'payment processing error',
          'unable to pay my bill online',
          'charge was rejected'
        ]
      },
      billing_inquiry: {
        label: 'Billing Inquiry',
        exemplars: [
          'I have a question about my bill',
          'what are the charges on my statement',
          'explain my latest bill',
          'why is my bill higher this month',
          'I need to understand my charges',
          'breakdown of my monthly charges',
          'when is my bill due'
        ]
      },
      refund_request: {
        label: 'Refund Request',
        exemplars: [
          'I want a refund',
          'please refund my last payment',
          'I was charged incorrectly need money back',
          'requesting a credit on my account',
          'overcharged and need refund',
          'duplicate charge on my account',
          'unauthorized charge please refund'
        ]
      },
      plan_change: {
        label: 'Plan Change',
        exemplars: [
          'I want to change my plan',
          'upgrade my subscription',
          'downgrade to a cheaper plan',
          'switch to a different tier',
          'change my billing cycle',
          'modify my current plan',
          'what plans are available'
        ]
      }
    }
  },
  technical_support: {
    label: 'Technical Support',
    intents: {
      connectivity: {
        label: 'Connectivity Issue',
        exemplars: [
          'my internet is not working',
          'cannot connect to the network',
          'wifi keeps dropping',
          'no signal on my device',
          'connection is very slow',
          'internet outage in my area',
          'losing connection frequently',
          'service is down'
        ]
      },
      device_issue: {
        label: 'Device Issue',
        exemplars: [
          'my device is not turning on',
          'phone screen is frozen',
          'device keeps restarting',
          'battery draining too fast',
          'device overheating',
          'hardware malfunction',
          'device not charging'
        ]
      },
      app_error: {
        label: 'Application Error',
        exemplars: [
          'the app keeps crashing',
          'getting an error message in the app',
          'app is not loading',
          'cannot login to the app',
          'app freezes when I try to use it',
          'feature not working in the application',
          'software update broke something'
        ]
      },
      service_outage: {
        label: 'Service Outage',
        exemplars: [
          'is there a service outage',
          'everything is down',
          'your service is not available',
          'widespread outage reported',
          'when will service be restored',
          'system is completely down',
          'major service disruption'
        ]
      }
    }
  },
  account: {
    label: 'Account Management',
    intents: {
      account_creation: {
        label: 'Account Creation',
        exemplars: [
          'I want to create a new account',
          'how do I sign up',
          'register for a new account',
          'open a new account',
          'set up my account',
          'start a new subscription'
        ]
      },
      account_modification: {
        label: 'Account Modification',
        exemplars: [
          'update my account information',
          'change my email address',
          'update my phone number',
          'modify my profile settings',
          'change my name on the account',
          'update my mailing address'
        ]
      },
      password_reset: {
        label: 'Password Reset',
        exemplars: [
          'I forgot my password',
          'need to reset my password',
          'cannot log in to my account',
          'locked out of my account',
          'password is not working',
          'reset my login credentials'
        ]
      },
      cancellation: {
        label: 'Account Cancellation',
        exemplars: [
          'I want to cancel my account',
          'close my account',
          'terminate my subscription',
          'stop my service',
          'I want to leave',
          'cancel everything',
          'end my membership'
        ]
      }
    }
  },
  sales: {
    label: 'Sales',
    intents: {
      product_inquiry: {
        label: 'Product Inquiry',
        exemplars: [
          'what products do you offer',
          'tell me about your services',
          'what features are included',
          'compare your products',
          'what is included in the package',
          'do you offer enterprise solutions'
        ]
      },
      upgrade: {
        label: 'Upgrade Request',
        exemplars: [
          'I want to upgrade my service',
          'what are the premium options',
          'upgrade to the next tier',
          'add more features to my plan',
          'interested in a higher plan',
          'want better service level'
        ]
      },
      new_service: {
        label: 'New Service',
        exemplars: [
          'I want to add a new service',
          'interested in your new offering',
          'add another line to my account',
          'start a new service',
          'bundle additional services',
          'add on to my existing plan'
        ]
      },
      pricing: {
        label: 'Pricing Inquiry',
        exemplars: [
          'how much does it cost',
          'what are your prices',
          'is there a discount available',
          'pricing for your services',
          'any promotions running',
          'cost comparison between plans',
          'do you have a student discount'
        ]
      }
    }
  },
  general: {
    label: 'General',
    intents: {
      general_inquiry: {
        label: 'General Inquiry',
        exemplars: [
          'I have a general question',
          'can you help me with something',
          'I need some information',
          'who do I contact for help',
          'where can I find more details',
          'I need assistance'
        ]
      },
      feedback: {
        label: 'Feedback',
        exemplars: [
          'I want to provide feedback',
          'I have a suggestion',
          'here is my review of the service',
          'want to share my experience',
          'feedback about recent interaction',
          'your service could improve'
        ]
      },
      complaint: {
        label: 'Complaint',
        exemplars: [
          'I want to file a complaint',
          'I am very unhappy with the service',
          'this is unacceptable',
          'worst experience ever',
          'I want to speak to a manager',
          'escalate this issue immediately',
          'your service is terrible'
        ]
      },
      compliment: {
        label: 'Compliment',
        exemplars: [
          'great service thank you',
          'the agent was very helpful',
          'excellent experience',
          'you solved my problem quickly',
          'wonderful customer support',
          'I appreciate the help'
        ]
      }
    }
  },

  // ═══════════════════════════════════════════════════
  // US Treasury — Citizen Contact Taxonomy
  // Top 20 reasons citizens contact Treasury, organized
  // into 5 logical domains
  // ═══════════════════════════════════════════════════

  tax_payments: {
    label: 'Tax Payments & Refunds',
    intents: {
      refund_status: {
        label: 'Tax Refund Status',
        exemplars: [
          'where is my tax refund',
          'check the status of my federal tax refund',
          'my tax refund has not arrived yet',
          'how long does it take to get my refund',
          'IRS refund tracking says it was sent but I have not received it',
          'my refund was supposed to be direct deposited last week',
          'when will I get my tax return money back',
          'refund check never came in the mail'
        ]
      },
      refund_offset: {
        label: 'Tax Refund Offset',
        exemplars: [
          'my tax refund was reduced and I do not know why',
          'Treasury took money from my refund for a debt',
          'refund offset notice what does this mean',
          'part of my tax refund was garnished',
          'why was my refund less than expected from the IRS',
          'I received a notice that my refund was applied to a federal debt',
          'Treasury offset took my entire tax refund',
          'how do I dispute a tax refund offset'
        ]
      },
      stimulus_payment: {
        label: 'Economic Impact Payment',
        exemplars: [
          'I never received my stimulus check',
          'where is my economic impact payment',
          'stimulus payment was sent to wrong account',
          'how do I claim a missing stimulus payment',
          'my stimulus check amount was wrong',
          'I am eligible for the stimulus but did not get it',
          'recovery rebate credit for missing stimulus',
          'economic impact payment status check'
        ]
      },
      tax_lien: {
        label: 'Federal Tax Lien',
        exemplars: [
          'there is a federal tax lien on my property',
          'how do I get a tax lien released',
          'IRS filed a lien and I need help removing it',
          'tax lien is affecting my credit report',
          'I paid my tax debt but the lien is still showing',
          'certificate of discharge for federal tax lien',
          'subordination of federal tax lien request',
          'how long does a federal tax lien last'
        ]
      }
    }
  },

  savings_bonds: {
    label: 'Savings Bonds & Securities',
    intents: {
      bond_redemption: {
        label: 'Savings Bond Redemption',
        exemplars: [
          'how do I cash in my savings bonds',
          'redeem my Series EE savings bond',
          'I have old paper savings bonds I want to cash',
          'what is my savings bond worth now',
          'where can I redeem a savings bond',
          'my savings bond has matured and I want to cash it',
          'convert paper bonds to electronic in TreasuryDirect',
          'Series I bond redemption before five years'
        ]
      },
      bond_purchase: {
        label: 'Savings Bond Purchase & Rates',
        exemplars: [
          'how do I buy I bonds',
          'what is the current I bond interest rate',
          'purchase savings bonds through TreasuryDirect',
          'annual I bond purchase limit',
          'how to buy savings bonds as a gift',
          'Series I bond vs Series EE bond which is better',
          'can I buy savings bonds with my tax refund',
          'I bond fixed rate and inflation rate explained'
        ]
      },
      bond_inheritance: {
        label: 'Inherited Savings Bonds',
        exemplars: [
          'I inherited savings bonds from a deceased relative',
          'how do I claim savings bonds from a deceased parent',
          'reissue savings bonds after death of owner',
          'my mother passed and left savings bonds in her name',
          'transfer inherited bonds to my TreasuryDirect account',
          'estate settlement for US savings bonds',
          'deceased owner savings bond claim process',
          'what documents do I need to claim inherited bonds'
        ]
      },
      marketable_securities: {
        label: 'Treasury Marketable Securities',
        exemplars: [
          'how do I buy Treasury bills',
          'T-bill auction schedule and rates',
          'purchase Treasury notes through TreasuryDirect',
          'TIPS inflation protected securities how do they work',
          'Treasury bond maturity and yield',
          'how to participate in a Treasury auction',
          'reinvest my maturing Treasury securities',
          'sell Treasury bonds before maturity'
        ]
      }
    }
  },

  treasury_payments: {
    label: 'Treasury Payments & Checks',
    intents: {
      check_replacement: {
        label: 'Lost or Stolen Treasury Check',
        exemplars: [
          'my Treasury check was lost in the mail',
          'someone stole and cashed my government check',
          'I never received my federal payment check',
          'how do I get a replacement Treasury check',
          'government check was damaged and I cannot deposit it',
          'request a reissue of a Treasury check',
          'my Social Security check was stolen from my mailbox',
          'forged endorsement on my Treasury check'
        ]
      },
      direct_deposit: {
        label: 'Direct Deposit Setup & Issues',
        exemplars: [
          'set up direct deposit for my federal payment',
          'change my direct deposit bank account for Social Security',
          'my direct deposit went to the wrong account',
          'federal payment was deposited to a closed bank account',
          'how do I update my banking information for federal payments',
          'switch from paper check to direct deposit',
          'direct deposit enrollment for federal benefits',
          'my bank rejected the federal direct deposit'
        ]
      },
      direct_express: {
        label: 'Direct Express Card Issues',
        exemplars: [
          'my Direct Express card is not working',
          'lost my Direct Express debit card need replacement',
          'check my Direct Express card balance',
          'unauthorized charges on my Direct Express card',
          'how do I activate my Direct Express card',
          'Direct Express card was declined at the store',
          'fees on my Direct Express card are too high',
          'switch from Direct Express to direct deposit'
        ]
      },
      unclaimed_money: {
        label: 'Unclaimed Money & Payments',
        exemplars: [
          'does the government owe me unclaimed money',
          'how do I find unclaimed federal payments',
          'search for unclaimed Treasury checks',
          'I think I have an uncashed government check',
          'undelivered federal tax refund from years ago',
          'find out if I have money owed to me by the government',
          'unclaimed savings bonds in my name',
          'how to claim forgotten federal payments'
        ]
      }
    }
  },

  debt_collection: {
    label: 'Debt Collection & Offsets',
    intents: {
      treasury_offset: {
        label: 'Treasury Offset Program',
        exemplars: [
          'what is the Treasury Offset Program',
          'my federal payment was reduced because of a debt',
          'Treasury offset took money from my Social Security',
          'how do I find out what debt caused my offset',
          'dispute a Treasury offset on my payment',
          'stop the Treasury Offset Program from taking my money',
          'federal salary offset for delinquent debt',
          'Treasury offset hardship exemption request'
        ]
      },
      cross_servicing: {
        label: 'Cross-Servicing & Debt Referral',
        exemplars: [
          'I received a letter from Treasury about a debt',
          'Bureau of the Fiscal Service debt collection notice',
          'my debt was referred to Treasury for collection',
          'how do I pay a federal debt sent to Treasury',
          'set up a payment plan for federal debt',
          'my federal debt was sent to a private collection agency',
          'cross-servicing debt what are my options',
          'Treasury debt collection interest and penalties'
        ]
      },
      wage_garnishment: {
        label: 'Administrative Wage Garnishment',
        exemplars: [
          'Treasury is garnishing my wages for a federal debt',
          'administrative wage garnishment notice from Treasury',
          'how do I stop wage garnishment for federal debt',
          'request a hearing for wage garnishment',
          'my employer received a wage garnishment order from Treasury',
          'financial hardship and wage garnishment relief',
          'what percentage of my wages can Treasury garnish',
          'wage garnishment exemption for low income'
        ]
      },
      offset_dispute: {
        label: 'Offset Dispute & Resolution',
        exemplars: [
          'I want to dispute a federal debt offset',
          'the offset on my payment is for a debt I already paid',
          'identity theft caused a false Treasury offset',
          'I do not owe this debt that was offset from my payment',
          'request a review of my Treasury offset',
          'offset dispute process and timeline',
          'wrong amount was offset from my payment',
          'how to prove a debt was paid to stop offset'
        ]
      }
    }
  },

  currency_compliance: {
    label: 'Currency & Compliance',
    intents: {
      damaged_currency: {
        label: 'Mutilated or Damaged Currency',
        exemplars: [
          'I have damaged money that the bank will not accept',
          'fire destroyed my cash how do I get it replaced',
          'submit mutilated currency to the Bureau of Engraving and Printing',
          'water damaged bills can they be exchanged',
          'how to mail damaged currency for redemption',
          'my dog chewed up paper money can I replace it',
          'partially destroyed bills replacement process',
          'Bureau of Engraving and Printing mutilated currency claim'
        ]
      },
      counterfeit_currency: {
        label: 'Counterfeit Currency',
        exemplars: [
          'I received a counterfeit bill how do I report it',
          'how to identify counterfeit money',
          'Secret Service counterfeit currency report',
          'someone gave me a fake hundred dollar bill',
          'can I get reimbursed for counterfeit money I received',
          'report counterfeit bills to local authorities',
          'security features on new hundred dollar bills',
          'what to do if I accidentally accepted counterfeit money'
        ]
      },
      ofac_sanctions: {
        label: 'OFAC Sanctions & Compliance',
        exemplars: [
          'my bank account was frozen because of OFAC',
          'I was flagged on the OFAC sanctions list by mistake',
          'apply for an OFAC specific license',
          'how do I get removed from the SDN list',
          'OFAC compliance question for my business',
          'blocked transaction due to sanctions screening',
          'false positive OFAC match on my name',
          'Treasury sanctions are affecting my wire transfer'
        ]
      },
      foia_request: {
        label: 'FOIA Request',
        exemplars: [
          'submit a FOIA request to the Treasury Department',
          'how do I file a Freedom of Information Act request',
          'FOIA request status check for Treasury records',
          'appeal a denied FOIA request with Treasury',
          'what Treasury records can I request through FOIA',
          'privacy act request for my personal records at Treasury',
          'FOIA response is taking too long from Treasury',
          'expedited processing for my FOIA request'
        ]
      }
    }
  },

  // ═══════════════════════════════════════════════════
  // Expanded Treasury — Tax Filing & Preparation
  // ═══════════════════════════════════════════════════

  tax_filing: {
    label: 'Tax Filing & Preparation',
    intents: {
      filing_assistance: {
        label: 'Tax Filing Assistance',
        exemplars: [
          'I need help filing my federal tax return',
          'how do I file my taxes online',
          'what forms do I need to file my taxes',
          'where can I get free tax preparation help',
          'VITA volunteer tax assistance locations near me',
          'do I need to file a tax return this year',
          'tax filing deadline extension request',
          'help me understand which tax form to use'
        ]
      },
      tax_transcript: {
        label: 'Tax Transcript Request',
        exemplars: [
          'I need a copy of my tax return transcript',
          'how do I get a tax transcript from the IRS',
          'request my wage and income transcript',
          'IRS transcript for my mortgage application',
          'verification of non-filing letter request',
          'get my tax records from previous years',
          'account transcript showing my tax history',
          'I need proof that I filed my taxes'
        ]
      },
      estimated_payments: {
        label: 'Estimated Tax Payments',
        exemplars: [
          'how do I make quarterly estimated tax payments',
          'when are estimated tax payments due',
          'I missed an estimated tax payment deadline',
          'calculate my estimated tax for this quarter',
          'set up automatic estimated tax payments through EFTPS',
          'penalty for not paying estimated taxes',
          'do I need to make estimated payments for self employment income',
          'estimated tax payment voucher Form 1040-ES'
        ]
      },
      installment_agreement: {
        label: 'Installment Agreement',
        exemplars: [
          'I owe the IRS and need a payment plan',
          'set up an installment agreement for my tax debt',
          'how much are the monthly payments for an IRS payment plan',
          'I cannot pay my taxes in full and need an installment agreement',
          'modify my existing IRS payment plan',
          'my installment agreement payment was missed',
          'streamlined installment agreement for tax debt under fifty thousand',
          'apply for a long-term IRS tax payment plan'
        ]
      },
      offer_compromise: {
        label: 'Offer in Compromise',
        exemplars: [
          'I want to settle my tax debt for less than I owe',
          'offer in compromise application process and eligibility',
          'can the IRS accept less than the full amount I owe',
          'I cannot afford to pay my full tax bill ever',
          'OIC pre-qualifier tool to check if I qualify',
          'submit an offer in compromise with doubt as to collectibility',
          'how long does an offer in compromise take to process',
          'appeal a rejected offer in compromise'
        ]
      }
    }
  },

  // ═══════════════════════════════════════════════════
  // Tax Identity & Fraud Protection
  // ═══════════════════════════════════════════════════

  tax_identity: {
    label: 'Tax Identity & Fraud',
    intents: {
      tax_identity_theft: {
        label: 'Tax Identity Theft',
        exemplars: [
          'someone filed a tax return using my Social Security number',
          'I am a victim of tax-related identity theft',
          'a fraudulent tax return was filed in my name',
          'my identity was stolen and used to claim a tax refund',
          'how do I report tax identity theft to the IRS',
          'I received a letter about a tax return I did not file',
          'request an IP PIN to protect my tax account',
          'identity protection personal identification number for tax filing'
        ]
      },
      itin_application: {
        label: 'ITIN Application',
        exemplars: [
          'I need an Individual Taxpayer Identification Number',
          'how do I apply for an ITIN',
          'ITIN application form W-7 instructions',
          'renew my expired ITIN number',
          'my ITIN application was rejected what do I do',
          'I am a non-citizen and need a tax identification number',
          'ITIN acceptance agent locations near me',
          'what documents are needed for an ITIN application'
        ]
      },
      innocent_spouse: {
        label: 'Innocent Spouse Relief',
        exemplars: [
          'I should not be liable for my ex-spouse tax debt',
          'innocent spouse relief application process',
          'my former spouse understated income on our joint return',
          'how do I request innocent spouse relief from the IRS',
          'separated liability election for a joint tax return',
          'equitable relief from joint and several tax liability',
          'my spouse hid income and now I owe their taxes',
          'Form 8857 request for innocent spouse relief'
        ]
      },
      tax_scam_reporting: {
        label: 'Tax Scam Reporting',
        exemplars: [
          'I received a call from someone claiming to be from the IRS',
          'report an IRS impersonation scam phone call',
          'I got a phishing email pretending to be from Treasury',
          'someone is threatening arrest if I do not pay taxes immediately',
          'how to report a tax scam or fraud scheme',
          'the IRS would never call demanding immediate payment right',
          'I gave personal information to a scammer pretending to be IRS',
          'report a fraudulent tax preparer'
        ]
      },
      taxpayer_advocate: {
        label: 'Taxpayer Advocate Service',
        exemplars: [
          'I need help from the Taxpayer Advocate Service',
          'my tax issue has not been resolved and I need an advocate',
          'how do I contact the Taxpayer Advocate office',
          'request TAS assistance for my unresolved tax problem',
          'I am experiencing financial hardship because of a tax issue',
          'the IRS is not resolving my case and I need advocacy help',
          'Form 911 request for taxpayer assistance order',
          'systemic issue affecting many taxpayers needs TAS attention'
        ]
      }
    }
  },

  // ═══════════════════════════════════════════════════
  // Tax Compliance & Enforcement
  // ═══════════════════════════════════════════════════

  tax_compliance: {
    label: 'Tax Compliance & Enforcement',
    intents: {
      audit_notice: {
        label: 'Audit Notice',
        exemplars: [
          'I received an audit notice from the IRS',
          'the IRS is examining my tax return',
          'how do I respond to an IRS audit letter',
          'what documents do I need for my tax audit',
          'correspondence audit requesting additional documentation',
          'I disagree with the audit findings on my return',
          'I got a CP2000 notice about unreported income',
          'appeal the results of my IRS examination'
        ]
      },
      penalty_abatement: {
        label: 'Penalty Abatement',
        exemplars: [
          'I want to request removal of IRS penalties',
          'first-time penalty abatement request eligibility',
          'reasonable cause for late filing penalty removal',
          'I had a valid reason for filing late and want the penalty removed',
          'abate failure to pay penalty due to financial hardship',
          'how to write a penalty abatement letter to the IRS',
          'the IRS assessed penalties and interest I cannot afford to pay',
          'penalty relief after a natural disaster'
        ]
      },
      tax_levy: {
        label: 'IRS Tax Levy',
        exemplars: [
          'the IRS is levying my bank account for taxes owed',
          'IRS wage levy is taking money from my paycheck',
          'how do I stop an IRS levy on my property',
          'request release of an IRS levy on my bank account',
          'my employer received an IRS wage levy notice',
          'the IRS took money from my bank account for back taxes',
          'financial hardship levy release request to the IRS',
          'I cannot pay my bills because of the IRS levy'
        ]
      },
      amended_return: {
        label: 'Amended Tax Return',
        exemplars: [
          'I need to correct a mistake on my tax return',
          'how do I file an amended tax return',
          'Form 1040-X amended return filing instructions',
          'I forgot to include income on my original tax return',
          'change my filing status on a previous year return',
          'amend my return to claim a deduction I missed',
          'how long does an amended return take to process',
          'track the status of my amended tax return'
        ]
      },
      back_taxes: {
        label: 'Back Taxes & Unfiled Returns',
        exemplars: [
          'I have not filed taxes in several years',
          'how do I catch up on unfiled tax returns',
          'I owe back taxes and do not know what to do',
          'what is the statute of limitations on unpaid taxes',
          'what are the consequences of not filing tax returns',
          'I want to come into compliance with past due returns',
          'the IRS filed a substitute for return on my behalf',
          'how far back do I need to file unfiled tax returns'
        ]
      }
    }
  },

  // ═══════════════════════════════════════════════════
  // TreasuryDirect Account Management
  // ═══════════════════════════════════════════════════

  treasury_accounts: {
    label: 'TreasuryDirect Accounts',
    intents: {
      treasurydirect_lockout: {
        label: 'TreasuryDirect Account Lockout',
        exemplars: [
          'I am locked out of my TreasuryDirect account',
          'cannot log in to TreasuryDirect website',
          'my TreasuryDirect account access is restricted',
          'reset my TreasuryDirect password and security questions',
          'TreasuryDirect account was locked for security reasons',
          'two-factor authentication is not working for TreasuryDirect login',
          'TreasuryDirect says my account is frozen',
          'how long does it take to unlock a TreasuryDirect account'
        ]
      },
      account_registration: {
        label: 'TreasuryDirect Registration',
        exemplars: [
          'how do I create a TreasuryDirect account',
          'set up a new TreasuryDirect account to buy bonds',
          'TreasuryDirect registration process and requirements',
          'what information do I need to open a TreasuryDirect account',
          'create a TreasuryDirect account for my business or entity',
          'entity account setup on TreasuryDirect platform',
          'open a TreasuryDirect account for a trust',
          'TreasuryDirect new account verification steps'
        ]
      },
      linked_bank_issues: {
        label: 'TreasuryDirect Bank Linking',
        exemplars: [
          'my bank account is not linking to TreasuryDirect',
          'change the bank account connected to my TreasuryDirect',
          'bank verification failed on TreasuryDirect',
          'add a new bank account to my TreasuryDirect profile',
          'remove an old bank account from TreasuryDirect',
          'TreasuryDirect bank connection error during setup',
          'my bank does not appear in the TreasuryDirect bank list',
          'ACH verification deposit for TreasuryDirect bank linking'
        ]
      },
      minor_account: {
        label: 'Minor Account Management',
        exemplars: [
          'set up a TreasuryDirect account for my minor child',
          'custodial account for a child on TreasuryDirect',
          'buy savings bonds as a gift for my grandchild',
          'transfer bonds to a minor TreasuryDirect account',
          'my child turned 18 and needs to convert their minor account',
          'manage savings bonds held in my child name',
          'gift box purchase on TreasuryDirect for a minor',
          'how does a linked minor account work on TreasuryDirect'
        ]
      }
    }
  },

  // ═══════════════════════════════════════════════════
  // Foreign Tax Obligations (Non-Citizen & Expat)
  // ═══════════════════════════════════════════════════

  foreign_tax: {
    label: 'Foreign Tax Obligations',
    intents: {
      fbar_reporting: {
        label: 'FBAR Foreign Account Reporting',
        exemplars: [
          'do I need to report my foreign bank accounts to FinCEN',
          'how to file an FBAR for my overseas accounts',
          'FinCEN Form 114 filing requirements and deadline',
          'I have foreign bank accounts over ten thousand dollars do I need to report',
          'I missed the FBAR filing deadline what should I do',
          'delinquent FBAR submission procedures and penalties',
          'streamlined filing for previously unreported foreign accounts',
          'what are the penalties for not reporting foreign bank accounts'
        ]
      },
      fatca_compliance: {
        label: 'FATCA Compliance',
        exemplars: [
          'what is FATCA and does it apply to me as a US person abroad',
          'Form 8938 foreign financial asset reporting requirements',
          'FATCA requirements for US citizens living abroad',
          'my foreign bank is asking about FATCA status what do I do',
          'foreign financial institution FATCA registration process',
          'FATCA intergovernmental agreement questions',
          'specified foreign financial assets reporting threshold',
          'I am a dual citizen do I need to report under FATCA'
        ]
      },
      nonresident_tax: {
        label: 'Non-Resident Tax Obligations',
        exemplars: [
          'I am a non-resident alien working in the United States on a visa',
          'what taxes do non-residents pay in the US',
          'Form 1040-NR non-resident alien income tax return',
          'tax withholding on payments to foreign persons',
          'non-resident alien tax filing requirements and deadlines',
          'I am on a work visa what are my US tax obligations',
          'dual-status tax return for the year I arrived in the US',
          'substantial presence test to determine my tax residency status'
        ]
      },
      treaty_benefits: {
        label: 'Tax Treaty Benefits',
        exemplars: [
          'my country has a tax treaty with the United States',
          'how to claim tax treaty benefits to reduce withholding',
          'Form W-8BEN treaty-based position for reduced tax rate',
          'tax treaty reduced withholding rate on dividends and interest',
          'which countries have income tax treaties with the US',
          'treaty exemption for foreign student and scholar income',
          'how to claim a tax treaty benefit on my return',
          'competent authority assistance under a bilateral tax treaty'
        ]
      },
      foreign_earned_income: {
        label: 'Foreign Earned Income',
        exemplars: [
          'I work overseas and want to exclude my foreign income from US tax',
          'foreign earned income exclusion eligibility and requirements',
          'Form 2555 foreign earned income exclusion',
          'bona fide residence test vs physical presence test for expats',
          'foreign housing exclusion or deduction for US citizens abroad',
          'I am a US citizen living abroad do I still need to file taxes',
          'foreign tax credit compared to foreign earned income exclusion',
          'US expat tax filing requirements and deadlines'
        ]
      }
    }
  },

  // ═══════════════════════════════════════════════════
  // Financial Crimes & Anti-Money Laundering
  // ═══════════════════════════════════════════════════

  financial_crimes: {
    label: 'Financial Crimes & AML',
    intents: {
      suspicious_activity: {
        label: 'Suspicious Activity Reporting',
        exemplars: [
          'I want to report suspicious financial transactions',
          'how to file a Suspicious Activity Report with FinCEN',
          'report potential money laundering activity',
          'suspicious wire transfer activity through my bank',
          'FinCEN SAR filing requirements and procedures',
          'I witnessed financial fraud at my workplace',
          'unusual large cash transactions that need reporting',
          'report suspected terrorist financing activity'
        ]
      },
      beneficial_ownership: {
        label: 'Beneficial Ownership Reporting',
        exemplars: [
          'what is the beneficial ownership information report',
          'does my company need to file a BOI report with FinCEN',
          'FinCEN beneficial ownership reporting deadline for my business',
          'who is considered a beneficial owner of a company',
          'how to file a BOI report with FinCEN online',
          'small company exemption from beneficial ownership reporting',
          'update my company beneficial ownership information',
          'penalties for not filing a beneficial ownership report'
        ]
      },
      bsa_compliance: {
        label: 'Bank Secrecy Act Compliance',
        exemplars: [
          'Bank Secrecy Act compliance requirements for my business',
          'currency transaction report filing for cash over ten thousand',
          'anti-money laundering program requirements',
          'BSA examination and enforcement questions',
          'customer due diligence rule requirements for banks',
          'how to file a CTR currency transaction report',
          'BSA E-Filing system registration and access',
          'recordkeeping requirements under the Bank Secrecy Act'
        ]
      },
      money_services: {
        label: 'Money Services Business',
        exemplars: [
          'register my money services business with FinCEN',
          'MSB registration requirements and renewal process',
          'money transmitter licensing requirements by state',
          'check cashing business FinCEN registration obligations',
          'currency exchange business compliance requirements',
          'prepaid access provider registration with FinCEN',
          'state vs federal money services business requirements',
          'FinCEN MSB registrant search to verify registration'
        ]
      },
      whistleblower: {
        label: 'Tax Fraud Whistleblower',
        exemplars: [
          'I want to report tax evasion and claim a whistleblower reward',
          'IRS whistleblower program how does it work',
          'submit information about tax fraud for a financial reward',
          'Form 211 application for whistleblower award',
          'what percentage reward does the IRS whistleblower program pay',
          'report a business that is hiding income from the IRS',
          'whistleblower protection for reporting tax fraud',
          'anonymous tip about a company evading taxes'
        ]
      }
    }
  },

  // ═══════════════════════════════════════════════════
  // Government Benefit Payments
  // ═══════════════════════════════════════════════════

  government_payments: {
    label: 'Government Benefit Payments',
    intents: {
      social_security_payment: {
        label: 'Social Security Payment Issues',
        exemplars: [
          'my Social Security payment did not arrive this month',
          'Social Security check was less than expected',
          'change direct deposit bank for my Social Security benefits',
          'Social Security payment schedule when will I get paid',
          'my Social Security payment was sent to the wrong bank account',
          'Social Security benefit payment was offset for a debt',
          'request re-issue of a lost Social Security check',
          'question about my monthly Social Security benefit amount'
        ]
      },
      federal_retirement: {
        label: 'Federal Retirement Payments',
        exemplars: [
          'my federal retirement pension payment is missing',
          'OPM retirement annuity payment question',
          'change direct deposit for my federal retirement benefits',
          'FERS annuity payment was not received this month',
          'CSRS retirement benefit payment schedule',
          'federal pension survivor benefit payment inquiry',
          'my federal retirement payment amount changed unexpectedly',
          'annuity payment issue from Office of Personnel Management'
        ]
      },
      veterans_payment: {
        label: 'Veterans Benefit Payments',
        exemplars: [
          'my VA benefits payment did not arrive on time',
          'Veterans Affairs disability compensation payment issue',
          'change direct deposit for my VA compensation benefits',
          'VA pension payment was reduced without explanation',
          'GI Bill education benefit payment is delayed',
          'veterans benefit payment schedule and dates',
          'my VA payment went to a closed bank account',
          'veteran disability compensation payment date question'
        ]
      },
      child_tax_credit: {
        label: 'Child Tax Credit Payments',
        exemplars: [
          'advance child tax credit payment questions and eligibility',
          'I did not receive my child tax credit payment',
          'opt out of advance child tax credit monthly payments',
          'child tax credit eligibility requirements for my family',
          'how much is the child tax credit per qualifying child',
          'child tax credit payment was the wrong amount',
          'do I need to repay excess child tax credit I received',
          'update my information for child tax credit payments'
        ]
      },
      disaster_relief: {
        label: 'Disaster Relief Payments',
        exemplars: [
          'disaster relief payment from FEMA or Treasury status',
          'natural disaster tax deadline extension',
          'I lost my tax records in a disaster and need to file',
          'federal disaster assistance payment has not arrived',
          'tax relief available after a hurricane earthquake or wildfire',
          'disaster loss deduction on my tax return',
          'FEMA individual assistance payment not received',
          'emergency financial assistance after a declared natural disaster'
        ]
      }
    }
  },

  // ═══════════════════════════════════════════════════
  // Estate & Gift Tax
  // ═══════════════════════════════════════════════════

  estate_gift_tax: {
    label: 'Estate & Gift Tax',
    intents: {
      estate_tax_filing: {
        label: 'Estate Tax Filing',
        exemplars: [
          'do I need to file a federal estate tax return',
          'Form 706 estate tax return filing requirements',
          'federal estate tax exemption amount this year',
          'how to file an estate tax return for a deceased person',
          'estate tax filing deadline and extension request',
          'portability election for unused estate tax exemption',
          'estate tax return for a large estate over the exemption',
          'what assets are included in the gross estate for tax purposes'
        ]
      },
      gift_tax: {
        label: 'Gift Tax',
        exemplars: [
          'do I need to pay gift tax on money I gave to family',
          'annual gift tax exclusion amount for this year',
          'Form 709 gift tax return filing requirements',
          'how much can I gift without paying taxes',
          'lifetime gift tax exemption and how it works',
          'gift tax on transfer of property to a family member',
          'do I owe gift tax for paying someone tuition or medical bills',
          'gift splitting between spouses on a gift tax return'
        ]
      },
      generation_skipping_tax: {
        label: 'Generation-Skipping Tax',
        exemplars: [
          'what is the generation-skipping transfer tax',
          'GST tax on gifts or bequests to grandchildren',
          'generation-skipping tax exemption amount',
          'how does the generation-skipping transfer tax work',
          'GST tax on distributions from a trust to skip persons',
          'allocating GST exemption to a trust',
          'taxable termination vs taxable distribution for GST',
          'planning to minimize generation-skipping transfer tax'
        ]
      },
      estate_valuation: {
        label: 'Estate Valuation',
        exemplars: [
          'how to value assets for estate tax purposes',
          'date of death valuation vs alternate valuation date',
          'appraisal requirements for estate tax return',
          'special use valuation for farm or business property',
          'valuation discounts for closely held business interests',
          'fair market value of real estate for estate tax',
          'stepped-up basis for inherited property',
          'how to determine the value of inherited stocks and bonds'
        ]
      }
    }
  },

  // ═══════════════════════════════════════════════════
  // Business Tax & Employer Obligations
  // ═══════════════════════════════════════════════════

  business_tax: {
    label: 'Business Tax & Compliance',
    intents: {
      ein_application: {
        label: 'EIN Application',
        exemplars: [
          'I need an Employer Identification Number for my business',
          'how do I apply for an EIN online',
          'apply for a federal tax ID number for my new company',
          'EIN application for a sole proprietorship',
          'I lost my EIN and need to look it up',
          'do I need a separate EIN for each business I own',
          'EIN for a nonprofit organization application',
          'how long does it take to receive an EIN'
        ]
      },
      payroll_tax: {
        label: 'Payroll & Employment Tax',
        exemplars: [
          'how do I deposit federal payroll taxes',
          'Form 941 quarterly employment tax return filing',
          'payroll tax deposit schedule and deadlines',
          'I am behind on payroll tax payments what do I do',
          'trust fund recovery penalty for unpaid payroll taxes',
          'how to correct a payroll tax return filing error',
          'employer responsibility for withholding income and FICA taxes',
          'Form 940 federal unemployment tax return'
        ]
      },
      business_tax_compliance: {
        label: 'Business Tax Compliance',
        exemplars: [
          'corporate income tax filing requirements and deadlines',
          'S corporation tax return Form 1120-S questions',
          'partnership tax return Form 1065 filing',
          'estimated tax payments for my business',
          'business tax deductions and credits I can claim',
          'how to handle IRS correspondence about my business return',
          'change my business entity type for tax purposes',
          'business tax compliance after receiving an IRS notice'
        ]
      },
      small_business_programs: {
        label: 'Small Business Tax Programs',
        exemplars: [
          'small business tax credits available this year',
          'qualified business income deduction section 199A',
          'research and development tax credit for small businesses',
          'work opportunity tax credit for hiring eligible employees',
          'small business health care tax credit eligibility',
          'employee retention credit questions and eligibility',
          'State Small Business Credit Initiative programs',
          'tax incentives for starting a new small business'
        ]
      }
    }
  }
};

// Flatten taxonomy into a lookup-friendly structure
function flattenTaxonomy() {
  const flat = [];
  for (const [domain, domainData] of Object.entries(TAXONOMY)) {
    for (const [intent, intentData] of Object.entries(domainData.intents)) {
      flat.push({
        domain,
        domainLabel: domainData.label,
        intent,
        intentLabel: intentData.label,
        fullKey: `${domain}.${intent}`,
        exemplars: intentData.exemplars
      });
    }
  }
  return flat;
}

module.exports = { TAXONOMY, flattenTaxonomy };
